// <auto-generated />
namespace ProductsApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class annotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(annotations));
        
        string IMigrationMetadata.Id
        {
            get { return "202003111328121_annotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
